<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>

<div class="row">
    <nav>
        <ul class="pager">
            <li class="previous"><?php echo $this->tag->a($this->url->get("wp_users/index"), "Go Back"); ?></li>
            <li class="next"><?php echo $this->tag->a($this->url->get("wp_users/new"), "Create"); ?></li>
        </ul>
    </nav>
</div>

<div class="page-header">
    <h1>Search result</h1>
</div>

<?php echo $this->getContent(); ?>

<div class="row">
    <table class="table table-bordered">
        <thead>
            <tr>
                <th>ID</th>
            <th>User Of Login</th>
            <th>User Of Pass</th>
            <th>User Of Nicename</th>
            <th>User Of Email</th>
            <th>User Of Url</th>
            <th>User Of Registered</th>
            <th>User Of Activation Of Key</th>
            <th>User Of Status</th>
            <th>Display Of Name</th>

                <th></th>
                <th></th>
            </tr>
        </thead>
        <tbody>
        <?php foreach ($page->getItems() as $wp_user): ?>
            <tr>
                <td><?php echo $wp_user->ID; ?></td>
            <td><?php echo $wp_user->user_login; ?></td>
            <td><?php echo $wp_user->user_pass; ?></td>
            <td><?php echo $wp_user->user_nicename; ?></td>
            <td><?php echo $wp_user->user_email; ?></td>
            <td><?php echo $wp_user->user_url; ?></td>
            <td><?php echo $wp_user->user_registered; ?></td>
            <td><?php echo $wp_user->user_activation_key; ?></td>
            <td><?php echo $wp_user->user_status; ?></td>
            <td><?php echo $wp_user->display_name; ?></td>

                <td><?php echo $this->tag->a($this->url->get("wp_users/edit/" . $wp_user->ID), "Edit"); ?></td>
                <td><?php echo $this->tag->a($this->url->get("wp_users/delete/" . $wp_user->ID), "Delete"); ?></td>
            </tr>
        <?php endforeach; ?>
        </tbody>
    </table>
</div>

<div class="row">
    <div class="col-sm-1">
        <p class="pagination" style="line-height: 1.42857;padding: 6px 12px;">
            <?php echo $page->getCurrent(), "/", $page->getTotalItems() ?>
        </p>
    </div>
    <div class="col-sm-11">
        <nav>
            <ul class="pagination">
                <li><?php echo $this->tag->a($this->url->get("wp_users/search"), "First", ['class' => 'page-link', 'id' => 'first']) ?></li>
                <li><?php echo $this->tag->a($this->url->get("wp_users/search?page=" . $page->getPrevious()), "Previous", ['class' => 'page-link', 'id' => 'previous']) ?></li>
                <li><?php echo $this->tag->a($this->url->get("wp_users/search?page=" . $page->getNext()), "Next", ['class' => 'page-link', 'id' => 'next']) ?></li>
                <li><?php echo $this->tag->a($this->url->get("wp_users/search?page=" . $page->getLast()), "Last", ['class' => 'page-link', 'id' => 'last']) ?></li>
            </ul>
        </nav>
    </div>
</div>
