name: Main CI

on: [push, pull_request]

env:
  DB_HOST: '127.0.0.1'

jobs:
  run:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: root
    steps:
      - uses: actions/checkout@v1

      - name: Init Database
        run: |
          mysql -uroot -h127.0.0.1 -proot -e 'CREATE DATABASE IF NOT EXISTS `invo`;'

      - name: Copy .env file
        run: cp .env.example .env

      - name: Setup PHP
        uses: shivammathur/setup-php@v1
        with:
          php-version: '7.2'
          tools: pecl
          extensions: mbstring, intl, json, phalcon4
          coverage: xdebug

      - name: Validate composer.json and composer.lock
        run: composer validate

      - name: Install Composer dependencies
        run: composer install --prefer-dist --no-progress --no-suggest

      - name: Run Psalm
        if: always()
        run: vendor/bin/psalm --show-info=false

      - name: Run tests
        if: always()
        run: |
          sudo php -S 0.0.0.0:90 -t public/ &
          vendor/bin/codecept build
          vendor/bin/codecept run acceptance
          vendor/bin/codecept run unit --coverage-xml=unit-coverage.xml
          vendor/bin/codecept run functional --coverage-xml=functional-coverage.xml

      - name: Upload coverage to Codecov
        if: always()
        uses: codecov/codecov-action@v1.0.3
        with:
          token: ${{secrets.CODECOV_TOKEN}}
          file: ./tests/_output/*-coverage.xml
